name: Sync Bitbucket to GitLab

on:
  push:
    branches:
      - main  # main 브랜치에 push가 발생할 때 실행

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone Bitbucket Repository
        run: |
          git clone --mirror https://github.com/kiyounggit/mirror_test.git repo
          cd repo
          git fetch --all

      - name: Push to GitLab
        run: |
          cd repo
          git remote add gitlab https://github.com/kiyounggit/gitlab_test.git
          git push gitlab --all
          git push gitlab --tags
